In [2]:
%run 'tools.ipynb'
init_printing(use_unicode=False, wrap_line=False, no_global=True)

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
...Done


In [3]:
np.linalg.eig(ket(0).array)

(array([ 1.,  0.]), array([[ 1.,  0.],
        [ 0.,  1.]]))

In [4]:
np.linalg.eig(ket(1).array)

(array([ 0.,  1.]), array([[ 1.,  0.],
        [ 0.,  1.]]))

In [5]:
np.linalg.eig(ket(1).array)

(array([ 0.,  1.]), array([[ 1.,  0.],
        [ 0.,  1.]]))

In [6]:
np.linalg.eig(probabilistic_pred(0.4,0.4,0.2).array)

(array([ 0.4,  0.4,  0.2]), array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

## Classical state

In [7]:
ss = State(np.diag([0.25, 0.025, 0.3, 0.425]),[2,2]);ss

[[ 0.25   0.     0.     0.   ]
 [ 0.     0.025  0.     0.   ]
 [ 0.     0.     0.3    0.   ]
 [ 0.     0.     0.     0.425]]

In [8]:
entanglement_test(ss)

False

In [9]:
np.linalg.eig(ss.array)

(array([ 0.25 ,  0.025,  0.3  ,  0.425]), array([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]))

In [10]:
N = 9

In [20]:
ps = [R(i*np.pi/(2*N)) for i in range(0,N+1)]; ps

[array([[ 1., -0.],
        [ 0.,  1.]]), array([[ 0.98480775, -0.17364818],
        [ 0.17364818,  0.98480775]]), array([[ 0.93969262, -0.34202014],
        [ 0.34202014,  0.93969262]]), array([[ 0.8660254, -0.5      ],
        [ 0.5      ,  0.8660254]]), array([[ 0.76604444, -0.64278761],
        [ 0.64278761,  0.76604444]]), array([[ 0.64278761, -0.76604444],
        [ 0.76604444,  0.64278761]]), array([[ 0.5      , -0.8660254],
        [ 0.8660254,  0.5      ]]), array([[ 0.34202014, -0.93969262],
        [ 0.93969262,  0.34202014]]), array([[ 0.17364818, -0.98480775],
        [ 0.98480775,  0.17364818]]), array([[ 6.123234e-17, -1.000000e+00],
        [ 1.000000e+00,  6.123234e-17]])]

In [24]:
ps = [channel_from_isometry(R(i*np.pi/(2*N)),[2],[2]) << point_pred(0,2) for i in range(0,N+1)]; ps

[[[1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]], [[ 0.96984631+0.j -0.17101007+0.j]
  [-0.17101007+0.j  0.03015369+0.j]], [[ 0.88302222+0.j -0.3213938 +0.j]
  [-0.3213938 +0.j  0.11697778+0.j]], [[ 0.75     +0.j -0.4330127+0.j]
  [-0.4330127+0.j  0.25     +0.j]], [[ 0.58682409+0.j -0.49240388+0.j]
  [-0.49240388+0.j  0.41317591+0.j]], [[ 0.41317591+0.j -0.49240388+0.j]
  [-0.49240388+0.j  0.58682409+0.j]], [[ 0.25     +0.j -0.4330127+0.j]
  [-0.4330127+0.j  0.75     +0.j]], [[ 0.11697778+0.j -0.3213938 +0.j]
  [-0.3213938 +0.j  0.88302222+0.j]], [[ 0.03015369+0.j -0.17101007+0.j]
  [-0.17101007+0.j  0.96984631+0.j]], [[ 3.74939946e-33+0.j -6.12323400e-17+0.j]
  [-6.12323400e-17+0.j  1.00000000e+00+0.j]]]

In [8]:
probs = [ss%[1,0] >= p for p in ps]; probs

In [28]:
C = sum(probs)

In [29]:
C = 0.5*(N + 1 + 1.0/np.tan(np.pi/(2*N))); nn

In [30]:
ps2 =  [Predicate(p.array/C,[2]) for p in ps]; ps2

[[[0.12762198+0.j 0.        +0.j]
  [0.        +0.j 0.        +0.j]], [[ 0.12377371+0.j -0.02182464+0.j]
  [-0.02182464+0.j  0.00384827+0.j]], [[ 0.11269304+0.j -0.04101691+0.j]
  [-0.04101691+0.j  0.01492894+0.j]], [[ 0.09571648+0.j -0.05526194+0.j]
  [-0.05526194+0.j  0.03190549+0.j]], [[ 0.07489165+0.j -0.06284156+0.j]
  [-0.06284156+0.j  0.05273033+0.j]], [[ 0.05273033+0.j -0.06284156+0.j]
  [-0.06284156+0.j  0.07489165+0.j]], [[ 0.03190549+0.j -0.05526194+0.j]
  [-0.05526194+0.j  0.09571648+0.j]], [[ 0.01492894+0.j -0.04101691+0.j]
  [-0.04101691+0.j  0.11269304+0.j]], [[ 0.00384827+0.j -0.02182464+0.j]
  [-0.02182464+0.j  0.12377371+0.j]], [[ 4.78505779e-34+0.j -7.81459241e-18+0.j]
  [-7.81459241e-18+0.j  1.27621979e-01+0.j]]]

In [31]:
sum([ss%[1,0] >= p for p in ps2])

In [33]:
def is_POVM(ps):
    ps = list(map(lambda x: x.array if isinstance(x, (Predicate,State)) else x, ps))
    return np.all(np.isclose(np.identity(ps[0].ndim), np.sum(ps, axis=0))) & np.all([is_positive(p) for p in ps])

In [34]:
list(map(lambda p: is_positive(p.array), ps))

[True, True, True, True, True, True, True, True, True, True]

In [35]:
list(map(lambda p: is_positive(p.array), ps2))

[True, True, True, True, True, True, True, True, True, True]

In [36]:
np.sum(list(map(lambda p: p.array, ps2)), axis=0)

array([[ 0.6381099+0.j, -0.3618901+0.j],
       [-0.3618901+0.j,  0.6381099+0.j]])

In [57]:
pE = np.identity(2) - np.sum(list(map(lambda p: p.array, ps2)), axis=0); pE

array([[0.3618901+0.j, 0.3618901+0.j],
       [0.3618901+0.j, 0.3618901+0.j]])

In [75]:
povm = list(map(lambda p: p.array, ps2)) + [pE]; povm

[array([[0.12762198+0.j, 0.        +0.j],
        [0.        +0.j, 0.        +0.j]]),
 array([[ 0.12377371+0.j, -0.02182464+0.j],
        [-0.02182464+0.j,  0.00384827+0.j]]),
 array([[ 0.11269304+0.j, -0.04101691+0.j],
        [-0.04101691+0.j,  0.01492894+0.j]]),
 array([[ 0.09571648+0.j, -0.05526194+0.j],
        [-0.05526194+0.j,  0.03190549+0.j]]),
 array([[ 0.07489165+0.j, -0.06284156+0.j],
        [-0.06284156+0.j,  0.05273033+0.j]]),
 array([[ 0.05273033+0.j, -0.06284156+0.j],
        [-0.06284156+0.j,  0.07489165+0.j]]),
 array([[ 0.03190549+0.j, -0.05526194+0.j],
        [-0.05526194+0.j,  0.09571648+0.j]]),
 array([[ 0.01492894+0.j, -0.04101691+0.j],
        [-0.04101691+0.j,  0.11269304+0.j]]),
 array([[ 0.00384827+0.j, -0.02182464+0.j],
        [-0.02182464+0.j,  0.12377371+0.j]]),
 array([[ 4.78505779e-34+0.j, -7.81459241e-18+0.j],
        [-7.81459241e-18+0.j,  1.27621979e-01+0.j]]),
 array([[0.3618901+0.j, 0.3618901+0.j],
        [0.3618901+0.j, 0.3618901+0.j]])]

In [76]:
is_POVM(povm)

True

In [68]:
is_unitary(R(0))

True

In [77]:
k = Kraus(povm, Dom([2]), Dom([2]))
c = k.as_channel()

In [78]:
povm

[array([[0.12762198+0.j, 0.        +0.j],
        [0.        +0.j, 0.        +0.j]]),
 array([[ 0.12377371+0.j, -0.02182464+0.j],
        [-0.02182464+0.j,  0.00384827+0.j]]),
 array([[ 0.11269304+0.j, -0.04101691+0.j],
        [-0.04101691+0.j,  0.01492894+0.j]]),
 array([[ 0.09571648+0.j, -0.05526194+0.j],
        [-0.05526194+0.j,  0.03190549+0.j]]),
 array([[ 0.07489165+0.j, -0.06284156+0.j],
        [-0.06284156+0.j,  0.05273033+0.j]]),
 array([[ 0.05273033+0.j, -0.06284156+0.j],
        [-0.06284156+0.j,  0.07489165+0.j]]),
 array([[ 0.03190549+0.j, -0.05526194+0.j],
        [-0.05526194+0.j,  0.09571648+0.j]]),
 array([[ 0.01492894+0.j, -0.04101691+0.j],
        [-0.04101691+0.j,  0.11269304+0.j]]),
 array([[ 0.00384827+0.j, -0.02182464+0.j],
        [-0.02182464+0.j,  0.12377371+0.j]]),
 array([[ 4.78505779e-34+0.j, -7.81459241e-18+0.j],
        [-7.81459241e-18+0.j,  1.27621979e-01+0.j]]),
 array([[0.3618901+0.j, 0.3618901+0.j],
        [0.3618901+0.j, 0.3618901+0.j]])]

In [80]:
k = Kraus(sqrt_diag(povm), Dom([2]), Dom([2]))
c = k.as_channel()

In [81]:
c

[[[[ 6.75480224e-01+0.j  1.11679832e-10+0.j]
   [ 1.11679832e-10+0.j  3.24519776e-01+0.j]]

  [[ 1.11679777e-10+0.j  3.24519781e-01+0.j]
   [ 3.24519776e-01+0.j -1.11679915e-10+0.j]]]


 [[[ 1.11679777e-10+0.j  3.24519776e-01+0.j]
   [ 3.24519781e-01+0.j -1.11679915e-10+0.j]]

  [[ 3.24519776e-01+0.j -1.11679888e-10+0.j]
   [-1.11679888e-10+0.j  6.75480224e-01+0.j]]]]

In [82]:
c << ket(0)

[[6.75480224e-01+0.j 1.11679832e-10+0.j]
 [1.11679832e-10+0.j 3.24519776e-01+0.j]]

In [28]:
ssss1 = ss % [1,0]; s1

[[0.275 0.   ]
 [0.    0.725]]

In [31]:
c >> s1

  --> Warning: trace is not 1.0 in state creation, but: (10+0j)


[[ 5.        +0.j -1.27603841+0.j]
 [-1.27603841+0.j  5.        +0.j]]

In [13]:
idn([2])@discard([2]) >> ss

[[0.275+0.j 0.   +0.j]
 [0.   +0.j 0.725+0.j]]

In [61]:
np.sum(ps,axis=0)

array([[ 6.21502615, -6.21502615],
       [ 6.21502615,  6.21502615]])

In [57]:
is_isometry(R(0))

True

In [58]:
[channel_from_isometry(R(i*np.pi/18), [2], [2]) << ket(0) for i in range(0,9+1)]

[[[1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]], [[ 0.96984631+0.j -0.17101007+0.j]
  [-0.17101007+0.j  0.03015369+0.j]], [[ 0.88302222+0.j -0.3213938 +0.j]
  [-0.3213938 +0.j  0.11697778+0.j]], [[ 0.75     +0.j -0.4330127+0.j]
  [-0.4330127+0.j  0.25     +0.j]], [[ 0.58682409+0.j -0.49240388+0.j]
  [-0.49240388+0.j  0.41317591+0.j]], [[ 0.41317591+0.j -0.49240388+0.j]
  [-0.49240388+0.j  0.58682409+0.j]], [[ 0.25     +0.j -0.4330127+0.j]
  [-0.4330127+0.j  0.75     +0.j]], [[ 0.11697778+0.j -0.3213938 +0.j]
  [-0.3213938 +0.j  0.88302222+0.j]], [[ 0.03015369+0.j -0.17101007+0.j]
  [-0.17101007+0.j  0.96984631+0.j]], [[ 3.74939946e-33+0.j -6.12323400e-17+0.j]
  [-6.12323400e-17+0.j  1.00000000e+00+0.j]]]

# FAQ

## Is $ s|_{p \And q} = s|_p|_q$?

In [6]:
s = random_state([2])
p = random_pred([2])
q = random_pred([2])
print(s, p, q)

[[ 0.51693559+0.j         -0.47337051+0.09720758j]
 [-0.47337051-0.09720758j  0.48306441+0.j        ]] [[0.97222701+0.j         0.09530779+0.11421474j]
 [0.09530779-0.11421474j 0.20323384+0.j        ]] [[ 0.52245229+0.j         -0.31265545+0.07195271j]
 [-0.31265545-0.07195271j  0.78446002+0.j        ]]


In [11]:
print(s/(p&q),
s/p/q)

  --> Warning: trace is not 1.0 in state creation, but: (0.9999999860526194-1.9313532488460874e-17j)
  --> Warning: trace is not 1.0 in state creation, but: (0.9999999946238839+1.3094661353238217e-16j)
[[ 0.63997044-3.86270650e-17j -0.43386475-1.94770068e-01j]
 [-0.43386475+1.94770068e-01j  0.36002955+1.93135325e-17j]] [[ 0.70571027-3.58839769e-17j -0.1062441 -4.38361946e-01j]
 [-0.1062441 +4.38361946e-01j  0.29428973-3.58839769e-17j]]


...apparently not.

# (memo)

In [4]:
instr(random_pred([2]))

[[[[ 0.27380835-8.87572009e-18j  0.1182118 -7.41489400e-02j]
   [ 0.1182118 +7.41489400e-02j  0.07111579-6.93889390e-18j]]

  [[ 0.1182118 +7.41489400e-02j  0.44520958-3.62630684e-17j]
   [ 0.03095583+6.40249284e-02j  0.19221119+1.20565422e-01j]]

  [[ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]
   [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]]

  [[ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]
   [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]]]


 [[[ 0.1182118 -7.41489400e-02j  0.03095583-6.40249284e-02j]
   [ 0.44520958-3.62630684e-17j  0.19221119-1.20565422e-01j]]

  [[ 0.07111579-6.93889390e-18j  0.19221119-1.20565422e-01j]
   [ 0.19221119+1.20565422e-01j  0.72390625-9.44607509e-17j]]

  [[ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]
   [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]]

  [[ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]
   [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j]]]


 [[[

## 3 dim

## Entaglement

In [5]:
convex_state_sum??

In [37]:
def ss(s_array):
    return convex_state_sum(*[(s_array[i,j], ket(i,j)) for i in range(2) for j in range(2)])

In [40]:
ss(np.array([[1,1],[1,1]])/4.0)

[[0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25]]

In [41]:
foo = np.array([[1,2,3],[3,4,5]])
type(foo)

numpy.ndarray

In [14]:
foo = (0.5,ket(0)), (0.5,ket(1))
s = convex_state_sum(*foo)

In [39]:
foo = [ket(0),ket(1),plus,minus,random_state(2)]

In [44]:
for phi in foo:
    for psi in foo:
        print(entanglement_test(phi@psi))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [35]:
ss = random_state([2,2])

In [36]:
entanglement_test(ss)

False

In [78]:
s0 = ket(0)
p0 = s0.as_pred()
(s0.dom, p0.dom)

([2], [2])

In [71]:
s00 = s0@s0
p00 = p0@p0
(s00.dom, p00.dom)

([2, 2], [2, 2])

In [72]:
c = idn([2])@discard([2])
(c.dom, c.cod)

([2, 2], [2])

In [73]:
c >> s0@s0

[[1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]

In [80]:
(idn([2])@discard([2]) << p0).dom

[2, 2]

In [52]:
(idn([2])@discard([2])).cod

[2]

In [7]:
ss % [0,1]

[[0.41695167+0.j         0.16293432-0.03333907j]
 [0.16293432+0.03333907j 0.58304833+0.j        ]]

In [18]:
ss.dom

[2, 2]

In [20]:
kron(ss,[4])

TypeError: can't multiply sequence by non-int of type 'State'